name: Compile

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v2

    # Get a list of changed files
    - run: |
      # Get the commit ID of the last push
      last_push=$(git rev-parse @{u})
      # Get a list of changed files since the last push
      git diff --name-only $last_push
      id: changed_files

    # Compile only the changed files
    - run: |
      for file in $(echo "${{ steps.changed_files.outputs.stdout }}"); do
        # Replace this with the command you use to compile your files
        if [ "${file##*.}" == "scad" ]; then
          openscad -o "${file%.*}.stl" "$file"
        fi
      done

#
#
