

# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: asciidoc pdf and html

on:
  push:
    paths:
      - 'openscad/**'
      - '**.adoc'
      - '**.asciidoc'
      - '.github/workflows/adoc.yml'
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull the containers required to build
        id: pull-containers
        run: |
          #This really just makes the pull shorter if there are more than one to pull
          docker pull $container_asciidoc &
          docker pull $container_openscad &
          wait
        env:
          container_asciidoc: ghcr.io/donnels/asciidoc:main
          container_openscad: ghcr.io/donnels/openscad:main

      - name: Conditioanl Scad build
        id: part-build-scad
        run: |
          git diff --name-only $GITHUB_SHA
          CHANGED_FILES=$(git diff --name-only $GITHUB_SHA)
          echo "changed files var: $CHANGED_FILES"
          echo "githubsha var: $GITHUB_SHA"
          for FILE in $CHANGED_FILES; do
          if [[ $FILE == *.scad ]]; then
          echo "testing the build: ${FILE%.*}.stl $FILE"
          fi
          done

      - name: run openscad container against this repo
        run: |
          cd openscad
          find . -name "*.scad" -type f | while read filename
          do  
          echo "looping into $filename"
          scadfile="$(basename "$filename")"
          file="$(basename -s".scad" "$filename")"
          dir="$(dirname "$filename")"
          echo "Moving into $dir"
          cd "$dir"
          echo "build it"
          echo "directory= $dir netto file= $file scadfile= $scadfile" 
          if [[ -f ${file}.png ]] && [[ -nt ${scadfile} ]]; then
          docker run --rm --name "openscad" --volume "$PWD":/data $container_openscad openscad --colorscheme Tomorrow -o "/data/${file}.png" "/data/${scadfile}"
          fi
          if [[ -f ${file}.stl ]] && [[ -nt ${scadfile} ]]; then
          docker run --rm --name "openscad" --volume "$PWD":/data $container_openscad openscad -o "/data/${file}.stl" "/data/${scadfile}"
          fi
          echo "back to previous"
          cd -
          echo
          done
          . ./indexer.sh
        env:
          container_asciidoc: ghcr.io/donnels/asciidoc:main
          container_openscad: ghcr.io/donnels/openscad:main

      - name: Make the PDFs and HTMLs
        id: asciidoc-2-html-and-pdf
        run: |
          docker run -v "$PWD":/documents/ --name asciidoc-to-pdf $container_asciidoc asciidoctor-pdf -D /documents/docs *.asciidoc
          docker run -v "$PWD":/documents/ --name asciidoc-to-html $container_asciidoc asciidoctor -D /documents/docs *.asciidoc
        env:
          container_asciidoc: ghcr.io/donnels/asciidoc:main
          container_openscad: ghcr.io/donnels/openscad:main

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m '[automated commit] push changed files from actions'
          git push
